openapi: 3.0.0
info:
  title: E-commerce Product API
  description: API for managing products and reviews in an e-commerce website
  version: 1.0.0

paths:
  /products:
    get:
      summary: Get a list of products
      responses:
        '200':
          description: A list of products
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
    post:
      summary: Create a new product
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        '201':
          description: Product created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
  /products/{productId}:
    get:
      summary: Get details of a specific product
      parameters:
        - name: productId
          in: path
          required: true
          description: The ID of the product to retrieve
          schema:
            type: integer
      responses:
        '200':
          description: Product details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
  /products/{productId}/reviews:
    get:
      summary: Get product reviews
      parameters:
        - name: productId
          in: path
          required: true
          description: The ID of the product to retrieve reviews for
          schema:
            type: integer
      responses:
        '200':
          description: Product reviews
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Review'
    post:
      summary: Add a new review for a product
      parameters:
        - name: productId
          in: path
          required: true
          description: The ID of the product to add the review to
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewReview'
      responses:
        '201':
          description: Review added successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Review'

components:
  schemas:
    Product:
      type: object
      properties:
        productId:
          type: integer
          description: The unique ID of the product
        productName:
          type: string
          description: The name of the product
        productImage:
          type: string
          format: uri
          description: URL of the product image
        price:
          type: number
          format: float
          description: The price of the product
        vendorId:
          type: integer
          description: The unique ID of the vendor
        vendorName:
          type: string
          description: The name of the vendor
    Review:
      type: object
      properties:
        reviewId:
          type: integer
          description: The unique ID of the review
        productId:
          type: integer
          description: The ID of the product being reviewed
        rating:
          type: integer
          description: The rating given in the review (e.g., 1 to 5 stars)
        comment:
          type: string
          description: The text comment provided in the review
    NewReview:
      type: object
      properties:
        productId:
          type: integer
          description: The ID of the product being reviewed
        rating:
          type: integer
          description: The rating given in the review (e.g., 1 to 5 stars)
        comment:
          type: string
          description: The text comment provided in the review
