openapi: 3.0.0
info:
  title: Sample API
  description: This is a sample API definition using Swagger/OpenAPI.
  version: 1.0.0
servers:
  - url: https://api.example.com/v1
paths:
  /users:
    get:
      summary: Get a list of users
      responses:
        '200':
          description: A list of users
          content:
            application/json:
              example:
                - id: 1
                  name: John Doe
                - id: 2
                  name: Jane Smith
    post:
      summary: Create a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
      responses:
        '201':
          description: User created successfully
          content:
            application/json:
              example:
                id: 3
                name: New User
  /users/{id}:
    parameters:
      - name: id
        in: path
        required: true
        description: The ID of the user to retrieve
        schema:
          type: integer
          format: int64
    get:
      summary: Get a user by ID
      responses:
        '200':
          description: User details
          content:
            application/json:
              example:
                id: 1
                name: John Doe
    put:
      summary: Update

